spring:
  application:
    name: api-gateway
server:
  port: 8080
zuul:
  routes:
    http-basic-playground-service:
      sensitiveHeaders: Cookie,Set-Cookie
#api-gateway:
#  redirect-services: http-basic-playground-service, session-based-playground-service

